services:

  mysql_prod:
    image: mysql:8
    container_name: mysql_prod
    env_file:
      - .env.prod
    ports:
      - "3309:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_prod_data:/var/lib/mysql
    networks:
      - prod_network

volumes:
  mysql_prod_data:

networks:
  prod_network: